-- MySQL Script generated by MySQL Workbench
-- Tue Mar  5 12:14:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`jogo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`jogo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`jogo` (
  `idJogo` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  PRIMARY KEY (`idJogo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plataforma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`plataforma` ;

CREATE TABLE IF NOT EXISTS `mydb`.`plataforma` (
  `idPlat` INT NOT NULL,
  `nomePlat` VARCHAR(45) NULL,
  PRIMARY KEY (`idPlat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idCli` INT NOT NULL,
  `nomeCli` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idCli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jogo_plataforma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`jogo_plataforma` ;

CREATE TABLE IF NOT EXISTS `mydb`.`jogo_plataforma` (
  `jogo_idJogo` INT NOT NULL,
  `plataforma_idPlat` INT NOT NULL,
  `precoDiario` INT NULL,
  PRIMARY KEY (`jogo_idJogo`, `plataforma_idPlat`),
  INDEX `fk_jogo_has_plataforma_plataforma1_idx` (`plataforma_idPlat` ASC) VISIBLE,
  INDEX `fk_jogo_has_plataforma_jogo_idx` (`jogo_idJogo` ASC) VISIBLE,
  CONSTRAINT `fk_jogo_has_plataforma_jogo`
    FOREIGN KEY (`jogo_idJogo`)
    REFERENCES `mydb`.`jogo` (`idJogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogo_has_plataforma_plataforma1`
    FOREIGN KEY (`plataforma_idPlat`)
    REFERENCES `mydb`.`plataforma` (`idPlat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`console`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`console` ;

CREATE TABLE IF NOT EXISTS `mydb`.`console` (
  `idCons` INT NOT NULL,
  `nomeCons` VARCHAR(45) NULL,
  `precoHora` INT NULL,
  PRIMARY KEY (`idCons`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`locacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`locacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`locacao` (
  `idLoc` INT NOT NULL,
  `nomeJogo` VARCHAR(45) NULL,
  `platJogo` VARCHAR(45) NULL,
  `cliente_idCli` INT NOT NULL,
  PRIMARY KEY (`idLoc`, `cliente_idCli`),
  INDEX `fk_locacao_cliente1_idx` (`cliente_idCli` ASC) VISIBLE,
  CONSTRAINT `fk_locacao_cliente1`
    FOREIGN KEY (`cliente_idCli`)
    REFERENCES `mydb`.`cliente` (`idCli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_locacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item_locacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`item_locacao` (
  `dias` DATE NULL,
  `quantidade` INT NULL,
  `locacao_idLoc` INT NOT NULL,
  `locacao_cliente_idCli` INT NOT NULL,
  `jogo_plataforma_jogo_idJogo` INT NOT NULL,
  `jogo_plataforma_plataforma_idPlat` INT NOT NULL,
  PRIMARY KEY (`locacao_idLoc`, `locacao_cliente_idCli`, `jogo_plataforma_jogo_idJogo`, `jogo_plataforma_plataforma_idPlat`),
  INDEX `fk_item_locacao_jogo_plataforma1_idx` (`jogo_plataforma_jogo_idJogo` ASC, `jogo_plataforma_plataforma_idPlat` ASC) VISIBLE,
  CONSTRAINT `fk_item_locacao_locacao1`
    FOREIGN KEY (`locacao_idLoc` , `locacao_cliente_idCli`)
    REFERENCES `mydb`.`locacao` (`idLoc` , `cliente_idCli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_locacao_jogo_plataforma1`
    FOREIGN KEY (`jogo_plataforma_jogo_idJogo` , `jogo_plataforma_plataforma_idPlat`)
    REFERENCES `mydb`.`jogo_plataforma` (`jogo_idJogo` , `plataforma_idPlat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente_console`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente_console` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente_console` (
  `cliente_idCli` INT NOT NULL,
  `console_idCons` INT NOT NULL,
  `inicio` DATETIME NOT NULL,
  `fim` DATETIME NOT NULL,
  PRIMARY KEY (`cliente_idCli`, `console_idCons`),
  INDEX `fk_cliente_has_console_console1_idx` (`console_idCons` ASC) VISIBLE,
  INDEX `fk_cliente_has_console_cliente1_idx` (`cliente_idCli` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_console_cliente1`
    FOREIGN KEY (`cliente_idCli`)
    REFERENCES `mydb`.`cliente` (`idCli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_console_console1`
    FOREIGN KEY (`console_idCons`)
    REFERENCES `mydb`.`console` (`idCons`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`acessorios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`acessorios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`acessorios` (
  `idAcess` INT NOT NULL,
  `nomeAcess` VARCHAR(45) NULL,
  `console_idCons` INT NOT NULL,
  PRIMARY KEY (`idAcess`, `console_idCons`),
  INDEX `fk_acessorios_console1_idx` (`console_idCons` ASC) VISIBLE,
  CONSTRAINT `fk_acessorios_console1`
    FOREIGN KEY (`console_idCons`)
    REFERENCES `mydb`.`console` (`idCons`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
